In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("datasets_4123_6408_framingham.csv")
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [22]:
df.sample(5)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
3778,0,47,1.0,1,20.0,0.0,0,0,1,186.0,139.0,85.0,27.90,80.0,125.0,0
4221,1,50,1.0,0,0.0,0.0,0,0,0,260.0,119.0,74.0,21.85,80.0,72.0,1
1758,0,57,2.0,0,0.0,0.0,0,0,0,333.0,128.0,84.0,25.69,75.0,NaN,0
357,0,54,2.0,1,3.0,0.0,0,1,1,231.0,127.5,83.0,21.31,70.0,115.0,0
3320,0,52,4.0,0,0.0,1.0,0,1,0,264.0,181.0,112.5,24.80,74.0,77.0,1

In [23]:
df.shape

(4240, 16)

In [24]:
df.drop("education",axis = 1, inplace = True)

In [25]:
df.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [26]:
bin_cols = ["male", "currentSmoker", "prevalentStroke", "prevalentHyp", "diabetes"]

for cols in bin_cols:
    mode_val = df[cols].mode()[0]
    df[cols].fillna(mode_val, inplace=True)

In [27]:
df.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [28]:
numeric_cols = ["cigsPerDay", "BPMeds", "totChol", "BMI", "glucose", "heartRate"]

for cols in numeric_cols:
    median_val = df[cols].median()
    df[cols].fillna(median_val, inplace=True)

In [29]:
df.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [30]:
df["TenYearCHD"].value_counts()

TenYearCHD
0    3596
1     644
Name: count, dtype: int64

In [31]:
from sklearn.utils import resample

df_majority = df[df["TenYearCHD"] == 0]
df_minority = df[df["TenYearCHD"] == 1]

df_minority_upsample = resample(df_minority,
                               replace=True,
                               n_samples=len(df_majority),
                               random_state=42)

df_balanced = pd.concat([df_majority, df_minority_upsample])

In [32]:
df_balanced["TenYearCHD"].value_counts()

TenYearCHD
0    3596
1    3596
Name: count, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df_balanced.drop(columns=["TenYearCHD"])
y = df_balanced["TenYearCHD"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
X_train

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose
1905,0,64,0,0.0,0.0,0,1,0,229.0,145.0,85.0,29.67,70.0,74.0
2075,0,37,1,20.0,0.0,0,0,0,166.0,112.0,73.5,21.64,75.0,93.0
1128,0,63,1,10.0,0.0,0,1,0,236.0,189.0,103.0,27.91,60.0,74.0
1782,0,65,0,0.0,0.0,0,1,0,245.0,171.0,89.0,23.07,82.0,93.0
241,1,65,1,15.0,0.0,0,1,0,219.0,148.0,90.0,29.35,77.0,97.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624,1,63,1,20.0,0.0,0,1,0,269.0,180.0,101.0,24.42,72.0,84.0
485,1,54,1,40.0,0.0,0,0,0,230.0,145.0,90.0,25.72,75.0,85.0
4232,1,68,0,0.0,0.0,0,1,0,176.0,168.0,97.0,23.14,60.0,79.0
952,1,66,1,30.0,0.0,0,0,1,234.0,114.5,62.5,28.62,75.0,216.0
1030,1,45,1,20.0,0.0,0,0,1,279.0,138.0,86.0,30.63,80.0,144.0

In [35]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [36]:
X_train_scaled

array([[-0.94172615,  1.4582083 , -1.02624378, ...,  0.840088  ,
        -0.50731448, -0.34072887],
       [-0.94172615, -1.66694628,  0.97442734, ..., -1.050363  ,
        -0.0898974 ,  0.25133934],
       [-0.94172615,  1.34246184,  0.97442734, ...,  0.42574258,
        -1.34214864, -0.34072887],
       ...,
       [ 1.06187982,  1.92119417, -1.02624378, ..., -0.6972277 ,
        -1.34214864, -0.18492145],
       [ 1.06187982,  1.68970124,  0.97442734, ...,  0.59289329,
        -0.0898974 ,  4.08420194],
       [ 1.06187982, -0.74097455,  0.97442734, ...,  1.0660946 ,
         0.32751968,  1.84057505]])

In [37]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
rf_model.fit(X_train_scaled, y_train)

y_pred = rf_model.predict(X_test_scaled)

In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score(y_test,y_pred)

0.9735927727588604

In [39]:
confusion_matrix(y_test, y_pred)

array([[702,  33],
       [  5, 699]], dtype=int64)

In [40]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.97       735
           1       0.95      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439

In [81]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Define a list of classifiers
classifiers = [
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    SVC(),
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    GaussianNB(),
    XGBClassifier()
]

# Create a DataFrame to store the results
results_df = pd.DataFrame(columns=['Model', 'Accuracy', 'F1-Score', 'Precision', 'Recall'])

# Train and evaluate each classifier
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)


    # calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{clf_name} Accuracy: {accuracy}")

    # Classification report
    print(f"Classification Report for {clf_name}:")
    print(classification_report(y_test, y_pred))
    
    # confusion matrix
    print(f"Classification Metrix for {clf_name}:")
    print(confusion_matrix(y_test, y_pred))
    print("_"*50)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    f1_score = report['weighted avg']['f1-score']
    precision = report['weighted avg']['precision']
    recall = report['weighted avg']['recall']
    
    # Append results to DataFrame
    results_df = pd.concat([results_df, pd.DataFrame([{'Model': clf_name, 'Accuracy': accuracy, 'F1-Score': f1_score, 
                                    'Precision': precision, 'Recall': recall}])], ignore_index=True)

results_df

RandomForestClassifier Accuracy: 0.9742876997915219
Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       735
           1       0.96      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439

Classification Metrix for RandomForestClassifier:
[[703  32]
 [  5 699]]
__________________________________________________

C:\Users\ssaty\AppData\Local\Temp\ipykernel_22388\3219759207.py:55: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame([{'Model': clf_name, 'Accuracy': accuracy, 'F1-Score': f1_score,

AdaBoostClassifier Accuracy: 0.6719944405837387
Classification Report for AdaBoostClassifier:
              precision    recall  f1-score   support

           0       0.69      0.66      0.67       735
           1       0.66      0.68      0.67       704

    accuracy                           0.67      1439
   macro avg       0.67      0.67      0.67      1439
weighted avg       0.67      0.67      0.67      1439

Classification Metrix for AdaBoostClassifier:
[[486 249]
 [223 481]]
__________________________________________________
GradientBoostingClassifier Accuracy: 0.7289784572619875
Classification Report for GradientBoostingClassifier:
              precision    recall  f1-score   support

           0       0.76      0.69      0.72       735
           1       0.70      0.77      0.74       704

    accuracy                           0.73      1439
   macro avg       0.73      0.73      0.73      1439
weighted avg       0.73      0.73      0.73      1439

Classification Metrix for GradientBoostingClassifier:
[[508 227]
 [163 541]]
__________________________________________________
LogisticRegression Accuracy: 0.6587908269631688
Classification Report for LogisticRegression:
              precision    recall  f1-score   support

           0       0.67      0.65      0.66       735
           1       0.65      0.66      0.66       704

    accuracy                           0.66      1439
   macro avg       0.66      0.66      0.66      1439
weighted avg       0.66      0.66      0.66      1439

Classification Metrix for LogisticRegression:
[[481 254]
 [237 467]]
__________________________________________________
SVC Accuracy: 0.6831132731063239
Classification Report for SVC:
              precision    recall  f1-score   support

           0       0.70      0.67      0.68       735
           1       0.67      0.70      0.68       704

    accuracy                           0.68      1439
   macro avg       0.68      0.68      0.68      1439
weighted avg       0.68      0.68      0.68      1439

Classification Metrix for SVC:
[[493 242]
 [214 490]]
__________________________________________________
KNeighborsClassifier Accuracy: 0.7873523280055594
Classification Report for KNeighborsClassifier:
              precision    recall  f1-score   support

           0       0.90      0.66      0.76       735
           1       0.72      0.92      0.81       704

    accuracy                           0.79      1439
   macro avg       0.81      0.79      0.78      1439
weighted avg       0.81      0.79      0.78      1439

Classification Metrix for KNeighborsClassifier:
[[482 253]
 [ 53 651]]
__________________________________________________
DecisionTreeClassifier Accuracy: 0.920778318276581
Classification Report for DecisionTreeClassifier:
              precision    recall  f1-score   support

           0       1.00      0.85      0.92       735
           1       0.86      1.00      0.92       704

    accuracy                           0.92      1439
   macro avg       0.93      0.92      0.92      1439
weighted avg       0.93      0.92      0.92      1439

Classification Metrix for DecisionTreeClassifier:
[[624 111]
 [  3 701]]
__________________________________________________
GaussianNB Accuracy: 0.5830437804030577
Classification Report for GaussianNB:
              precision    recall  f1-score   support

           0       0.56      0.91      0.69       735
           1       0.72      0.24      0.36       704

    accuracy                           0.58      1439
   macro avg       0.64      0.58      0.53      1439
weighted avg       0.64      0.58      0.53      1439

Classification Metrix for GaussianNB:
[[668  67]
 [533 171]]
__________________________________________________
XGBClassifier Accuracy: 0.906184850590688
Classification Report for XGBClassifier:
              precision    recall  f1-score   support

           0       0.96      0.85      0.90       735
           1       0.86      0.96      0.91       704

    accuracy                           0.91      1439
   macro avg       0.91      0.91      0.91      1439
weighted avg       0.91      0.91      0.91      1439

Classification Metrix for XGBClassifier:
[[625 110]
 [ 25 679]]
__________________________________________________

                        Model  Accuracy  F1-Score  Precision    Recall
0      RandomForestClassifier  0.974288  0.974289   0.974977  0.974288
1          AdaBoostClassifier  0.671994  0.672015   0.672474  0.671994
2  GradientBoostingClassifier  0.728978  0.728702   0.731320  0.728978
3          LogisticRegression  0.658791  0.658830   0.659053  0.658791
4                         SVC  0.683113  0.683126   0.683656  0.683113
5        KNeighborsClassifier  0.787352  0.783833   0.812481  0.787352
6      DecisionTreeClassifier  0.920778  0.920459   0.930679  0.920778
7                  GaussianNB  0.583044  0.530092   0.635597  0.583044
8               XGBClassifier  0.906185  0.905977   0.912148  0.906185

In [42]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\ssaty\appdata\roaming\python\python311\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.11.4)
Note: you may need to restart the kernel to use updated packages.

In [83]:
results_df

                        Model  Accuracy  F1-Score  Precision    Recall
0      RandomForestClassifier  0.974288  0.974289   0.974977  0.974288
1          AdaBoostClassifier  0.671994  0.672015   0.672474  0.671994
2  GradientBoostingClassifier  0.728978  0.728702   0.731320  0.728978
3          LogisticRegression  0.658791  0.658830   0.659053  0.658791
4                         SVC  0.683113  0.683126   0.683656  0.683113
5        KNeighborsClassifier  0.787352  0.783833   0.812481  0.787352
6      DecisionTreeClassifier  0.920778  0.920459   0.930679  0.920778
7                  GaussianNB  0.583044  0.530092   0.635597  0.583044
8               XGBClassifier  0.906185  0.905977   0.912148  0.906185

In [89]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Instantiate the RandomForestClassifier
rf_classifier = RandomForestClassifier()

# Train the RandomForestClassifier
rf_classifier.fit(X_train_scaled, y_train)

# Predict on the test set
y_pred_rf = rf_classifier.predict(X_test_scaled)

# Calculate accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Classifier Accuracy:", accuracy_rf)

# Classification report
print("Classification Report for Random Forest Classifier:")
print(classification_report(y_test, y_pred_rf))

# Confusion matrix
print("Confusion Matrix for Random Forest Classifier:")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Classifier Accuracy: 0.9722029186935371
Classification Report for Random Forest Classifier:
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       735
           1       0.95      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439

Confusion Matrix for Random Forest Classifier:
[[700  35]
 [  5 699]]

In [105]:
print("predict class", rf_classifier.predict(X_test_scaled[10].reshape(1,-1))[0])
print("actual class ", y_test.iloc[10])

predict class 0
actual class  0

In [111]:
print("predict class", rf_classifier.predict(X_test_scaled[200].reshape(1,-1))[0])
print("actual class ", y_test.iloc[200])

predict class 1
actual class  1

In [119]:
import pickle
pickle.dump(rf_classifier,open("Models/rf_classifier.pkl",'wb'))
pickle.dump(scaler,open("Models/scaler.pkl",'wb'))

In [123]:
import pickle

# Load the RandomForestClassifier model
with open("Models/rf_classifier.pkl", "rb") as file:
    rf_classifier = pickle.load(file)

# Load the scaler
with open("Models/scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

In [125]:
import numpy as np

def predict(rf_classifier, scaler, male, age, currentSmoker, cigsPerDay, BPMeds, prevalentStroke, prevalentHyp, diabetes, totChol, sysBP, diaBP, BMI, heartRate, glucose):
    # Encode categorical variables
    male_encoded = 1 if male.lower() == "male" else 0
    currentSmoker_encoded = 1 if currentSmoker.lower() == "yes" else 0
    BPMeds_encoded = 1 if BPMeds.lower() == "yes" else 0
    prevalentStroke_encoded = 1 if prevalentStroke.lower() == "yes" else 0
    prevalentHyp_encoded = 1 if prevalentHyp.lower() == "yes" else 0
    diabetes_encoded = 1 if diabetes.lower() == "yes" else 0


     # Prepare features array
    features = np.array([[male_encoded, age, currentSmoker_encoded, cigsPerDay, BPMeds_encoded, prevalentStroke_encoded, prevalentHyp_encoded, diabetes_encoded, totChol, sysBP, diaBP, BMI, heartRate, glucose]])
    
    # scalling
    scaled_features = scaler.transform(features)
    
    # predict by model
    result = rf_classifier.predict(scaled_features)
    
    return result[0]

In [131]:
# test 1:
male = "female"
age = 56.00
currentSmoker = "yes"
cigsPerDay = 3.00
BPMeds = "no"
prevalentStroke = "no"
prevalentHyp = "yes"
diabetes = 'no'
totChol = 285.00
sysBP = 145.00
diaBP = 100.00
BMI = 30.14
heartRate = 80.00
glucose = 86.00

result = predict(rf_classifier, scaler, male, age, currentSmoker, cigsPerDay, BPMeds, prevalentStroke, prevalentHyp, diabetes, totChol, sysBP, diaBP, BMI, heartRate, glucose)

if result == 1:
    print("The Patient has Heart Diseas")
else: 
    print("The Patiennt has No Heart Deseas")

The Patiennt has No Heart Deseas

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [141]:
import sklearn 
sklearn.__version__

'1.2.2'

In [135]:
import numpy
numpy.__version__

'1.26.4'